plugin: rest

resources:
- method: GET
  path: /static-exact-delay
  response:
    staticData: "Belated hello"

    # delay 500ms before responding
    delay:
      exact: 500

- method: GET
  path: /static-range-delay
  response:
    staticData: "Belated hello"

    # delay 500ms before responding
    delay:
      min: 200
      max: 400
